apiVersion: 0.1.0
kind: ksonnet.io/app
libraries:
  argo:
    name: argo
    registry: kubeflow
  core:
    name: core
    registry: kubeflow
  examples:
    name: examples
    registry: kubeflow
  katib:
    name: katib
    registry: kubeflow
  mpi-job:
    name: mpi-job
    registry: kubeflow
  pytorch-job:
    name: pytorch-job
    registry: kubeflow
  seldon:
    name: seldon
    registry: kubeflow
  tf-serving:
    name: tf-serving
    registry: kubeflow
name: ks_app
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: fs
    uri: /home/jlewi/tmp/kubeflow_v0.3.0-rc-1/kubeflow
version: 0.0.1
