apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://35.196.4.129
    k8sVersion: v1.7.0
    path: default
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: 3da7eb254cefd6a8a79ed7db57a30adfb91b734e
      refSpec: master
    name: core
    registry: kubeflow
  pytorch-job:
    gitVersion:
      commitSha: 3da7eb254cefd6a8a79ed7db57a30adfb91b734e
      refSpec: master
    name: pytorch-job
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 3da7eb254cefd6a8a79ed7db57a30adfb91b734e
      refSpec: master
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: 3da7eb254cefd6a8a79ed7db57a30adfb91b734e
      refSpec: master
    name: tf-serving
    registry: kubeflow
name: app
registries:
  kubeflow:
    gitVersion:
      commitSha: 3be196cfa1d68d9a33e0674c133ffbbcc3e57d46
      refSpec: v0.2.0-rc.1
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.2.0-rc.1/kubeflow
version: 0.0.1
