apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://35.196.4.129
    k8sVersion: v1.9.6
    path: default
kind: ksonnet.io/app
libraries:
  core:
    name: core
    registry: kubeflow
  pytorch-job:
    name: pytorch-job
    registry: kubeflow
  tf-job:
    name: tf-job
    registry: kubeflow
  tf-serving:
    name: tf-serving
    registry: kubeflow
name: app
registries:
  kubeflow:
    protocol: fs
    uri: file:///opt/registries/kubeflow/kubeflow
version: 0.0.1
